### ISSUE TITLE
cart.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [megabinar/angularHT#3]
У меня не возникало ошибок по поводу двух async в темплейте, хотя не думаю, что их два надо В подписке на товары, вы можете определять видимость корзины, просто проверив, какая длина коллекции, что пришла на вход.
 // TODO bug if both async in template???????
  products$: Observable<string[]>;
  cartVisible$: Observable<boolean>;

Но на самом деле, думаю, лучше эту директиву вынести на хост тег <app-cart *ngIf="..."></app-cart>Так не будет создаваться компонент. А в вашем случае он создается, но не отображается.
Напишите, какая ошибка возникает.

**Comment by megabinar** [comment]
Это да, но хотелось бы разобраться с этой проблемой. 
Ошибки нет, есть баг. При использовании в обоих директивах async: в ngIf и внутри ngFor. Когда товаров было 0 а стало 1 - ngif срабатывает a ngFor нет, и список остается пустым. При добавлении второго товара оба отрабатывают и товаров видно сразу 2. Можно попробовать раскоментив код (и закоментив синхронный, это только в темплейте).

**Comment by VZhyrytskiy** [comment]
Да, я увидел вариант описаный вами. Покрутил, но у меня тоже не получилось заставить работать с двумя async. Вариант ngIf + async, ngFor - тоже не заработал как хотелось бы. Может быть баг, может быть есть какая-то специфика работы фильтра async при подписке, которую я не знаю.
